# Base values that are common across all clusters.
# Cluster-specific overrides will be provided in separate files

global:
  # These are placeholders and MUST be overridden
  clusterName: "default-cluster"
  projectId: "default-project"
  region: "default-region"
  serviceAccount: "karpenter-system@{{ $.Values.global.projectId }}.iam.gserviceaccount.com"

nodePools:
  - name: foobar
    annotations:
      kubernetes.io/description: "General purpose NodePool for foobar on {{ $.Values.global.clusterName }}"
    disruption:
      budgets:
      - nodes: "3"
      consolidateAfter: 90s
      consolidationPolicy: WhenEmpty
    template:
      metadata:
        labels:
          environment: "foobar"
      spec:
        terminationGracePeriod: 48h
        taints:
        - key: environment
          value: "foobar"
          effect: NoSchedule
        requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: [ "on-demand", "spot" ]
        - key: "karpenter.k8s.gcp/instance-family"
          operator: In
          values: [ "c3-standard" ]
        - key: "karpenter.k8s.gcp/instance-cpu"
          operator: Lt
          values: [ "16" ]
        - key: "kubernetes.io/arch"
          operator: In
          values: [ "amd64" ]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "europe-west4-a" ]
    nodeClass:
      imageSelectorTerms:
      - alias: ContainerOptimizedOS@latest
      networkTags:
      - "k8s-{{ $.Values.global.clusterName }}"
      disks:
      - boot: true
        sizeGiB: 128
        category: "pd-ssd"
      kubeletConfiguration:
        maxPods: 80
        cpuCFSQuota: false
      tags:
        foo: "bar"
